package com.enterprise.department.mapper;

import com.enterprise.department.dto.EmployeeDTO;
import com.enterprise.department.entity.Employee;
import org.springframework.stereotype.Component;

/**
 * Mapper for Employee entity and DTO conversion
 */
@Component
public class EmployeeMapper {

    /**
     * Convert Employee entity to DTO
     *
     * @param employee Employee entity
     * @return EmployeeDTO
     */
    public EmployeeDTO toDTO(Employee employee) {
        if (employee == null) {
            return null;
        }

        EmployeeDTO dto = new EmployeeDTO();
        dto.setId(employee.getId());
        dto.setName(employee.getName());
        dto.setEmail(employee.getEmail());
        dto.setPosition(employee.getPosition());
        dto.setSalary(employee.getSalary());

        if (employee.getDepartment() != null) {
            dto.setDepartmentId(employee.getDepartment().getId());
            dto.setDepartmentName(employee.getDepartment().getName());
        }

        dto.setCreatedAt(employee.getCreatedAt());
        dto.setUpdatedAt(employee.getUpdatedAt());

        return dto;
    }

    /**
     * Convert EmployeeDTO to entity (without ID - ID is generated)
     *
     * @param dto EmployeeDTO
     * @return Employee entity
     */
    public Employee toEntity(EmployeeDTO dto) {
        if (dto == null) {
            return null;
        }

        Employee employee = new Employee();
        // Note: ID is not set here, it will be generated by EmployeeIdGenerator
        employee.setName(dto.getName());
        employee.setEmail(dto.getEmail());
        employee.setPosition(dto.getPosition());
        employee.setSalary(dto.getSalary());

        return employee;
    }

    /**
     * Update existing employee entity from DTO
     *
     * @param dto      EmployeeDTO
     * @param employee Existing employee entity
     */
    public void updateEntityFromDTO(EmployeeDTO dto, Employee employee) {
        if (dto == null || employee == null) {
            return;
        }

        employee.setName(dto.getName());
        employee.setEmail(dto.getEmail());
        employee.setPosition(dto.getPosition());
        employee.setSalary(dto.getSalary());
        // Note: Department is not updated here, handled separately in service
    }
}
